name: Go

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: v1

    - name: Build Consumer
      run: go build -v -o build/ ./src/tsconsumer

    - name: Build Producer
      env:
        GOARCH: arm
        GOARM: 6
      run: go build -v -o build/ ./src/producer
      
    - name: artifacts
      run: ls -la build
