name: build

on:
  push:
    branches: [ main ]
    tags: 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: v1

    - name: Build Consumer
      run: go build -v -o build/ ./src/tsconsumer

    - name: Build Producer
      env:
        GOARCH: arm
        GOARM: 6
      run: go build -v -o build/ ./src/tsproducer
      
    - name: List Artifacts
      run: ls -la build && file build/*
      
    - name: Publish
      if: startsWith(github.ref, 'refs/tags/v')
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/*"
        token: ${{ secrets.GITHUB_TOKEN }}
